// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddProject struct {
	Projects []string `json:"projects"`
}

type ArchivePhase struct {
	Archived *bool `json:"archived"`
}

type ArchiveProject struct {
	Archived *bool `json:"archived"`
}

type AuthRes struct {
	Iss           string `json:"iss"`
	Sub           string `json:"sub"`
	Azp           string `json:"azp"`
	Aud           string `json:"aud"`
	Iat           string `json:"iat"`
	Exp           string `json:"exp"`
	Email         string `json:"email"`
	EmailVerified string `json:"emailVerified"`
	Name          string `json:"name"`
	Picture       string `json:"picture"`
	GivenName     string `json:"givenName"`
	FamilyName    string `json:"familyName"`
	Locale        string `json:"locale"`
}

type AuthToken struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type ChangeOwnerOrg struct {
	OwnerID string `json:"ownerID"`
}

type CustomClaims struct {
	UserName  string `json:"userName"`
	ExpiresAt int    `json:"expiresAt"`
	Issuer    string `json:"issuer"`
}

type EditOrg struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type EditPhase struct {
	Name      string `json:"name"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
}

type EditProject struct {
	Name             string `json:"name"`
	Description      string `json:"description"`
	StartDate        string `json:"startDate"`
	EndDate          string `json:"endDate"`
	Archived         *bool  `json:"archived"`
	ProjectLeadID    string `json:"projectLeadID"`
	ProjectMonitorID string `json:"projectMonitorID"`
	CurrentPhase     string `json:"currentPhase"`
}

type GInfoRes struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	EmailVerified string `json:"emailVerified"`
	Name          string `json:"name"`
	GivenName     string `json:"given_name"`
	FamilyName    string `json:"family_name"`
	Picture       string `json:"picture"`
	Locale        string `json:"locale"`
	Hd            string `json:"hd"`
}

type LoginRequest struct {
	GID         string `json:"gID"`
	AccessToken string `json:"accessToken"`
	Email       string `json:"email"`
	Fname       string `json:"fname"`
	Lname       string `json:"lname"`
	Image       string `json:"image"`
}

type NewOrg struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	NumMembers  *int     `json:"numMembers"`
	OwnerID     *string  `json:"ownerID"`
	AdminsID    []string `json:"adminsID"`
	MembersID   []string `json:"membersID"`
}

type NewPhase struct {
	Name      string   `json:"name"`
	ProjectID string   `json:"projectID"`
	Progress  int      `json:"progress"`
	Weight    int      `json:"weight"`
	StartDate string   `json:"startDate"`
	EndDate   string   `json:"endDate"`
	States    []string `json:"states"`
	Archived  *bool    `json:"archived"`
}

type NewProject struct {
	Name             string    `json:"name"`
	Description      *string   `json:"description"`
	StartDate        string    `json:"startDate"`
	EndDate          string    `json:"endDate"`
	OrganizationID   string    `json:"organizationID"`
	MembersID        []*string `json:"membersID"`
	ProjectLeadID    string    `json:"projectLeadID"`
	ProjectMonitorID *string   `json:"projectMonitorID"`
	Archived         *bool     `json:"archived"`
}

type NewProjectMod struct {
	Name             string    `json:"name"`
	Description      *string   `json:"description"`
	Progress         int       `json:"progress"`
	Weight           int       `json:"weight"`
	StartDate        string    `json:"startDate"`
	EndDate          string    `json:"endDate"`
	OrganizationID   string    `json:"organizationID"`
	CreatedByID      string    `json:"createdByID"`
	MembersID        []*string `json:"membersID"`
	ProjectLeadID    string    `json:"projectLeadID"`
	ProjectMonitorID *string   `json:"projectMonitorID"`
	Archived         bool      `json:"archived"`
}

type NewSubtask struct {
	Name         *string `json:"name"`
	Description  *string `json:"description"`
	AssignedID   *string `json:"assignedID"`
	OrgID        *string `json:"orgID"`
	AuthorID     string  `json:"authorID"`
	PhaseID      *string `json:"phaseID"`
	Progress     *int    `json:"progress"`
	Weight       *int    `json:"weight"`
	State        *string `json:"state"`
	DeadlineDate *string `json:"deadlineDate"`
	DeadlineTime *string `json:"deadlineTime"`
	CreateDate   *string `json:"createDate"`
	CreateTime   *string `json:"createTime"`
	Archived     *bool   `json:"archived"`
	ParentID     *string `json:"parentID"`
}

type NewTask struct {
	Name             string    `json:"name"`
	Description      *string   `json:"description"`
	AssignedID       *string   `json:"assignedID"`
	OrgID            *string   `json:"orgID"`
	AuthorID         string    `json:"authorID"`
	PhaseID          *string   `json:"phaseID"`
	Progress         *int      `json:"progress"`
	Weight           *int      `json:"weight"`
	Ready            *bool     `json:"ready"`
	State            *string   `json:"state"`
	DeadlineDate     string    `json:"deadlineDate"`
	DeadlineTime     string    `json:"deadlineTime"`
	CreateDate       *string   `json:"createDate"`
	CreateTime       *string   `json:"createTime"`
	Archived         *bool     `json:"archived"`
	NextTasks        []*string `json:"nextTasks"`
	SubtaskAssignees []*string `json:"subtaskAssignees"`
	SubtaskDeadlines []*string `json:"subtaskDeadlines"`
	SoonReady        *bool     `json:"soonReady"`
	FirstTask        *bool     `json:"firstTask"`
}

type NewUser struct {
	GID   string `json:"gID"`
	Fname string `json:"fname"`
	Lname string `json:"lname"`
	Email string `json:"email"`
	Image string `json:"image"`
}

type Organization struct {
	ID           string   `json:"id" bson:"_id"`
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	NumMembers   int      `json:"numMembers"`
	MembersID    []string `json:"membersID"`
	AdminsID     []string `json:"adminsID"`
	OwnerID      string   `json:"ownerID"`
	Projects     []string `json:"projects"`
	OrgTasks     []*Task  `json:"orgTasks"`
	OrgReminders []string `json:"orgReminders"`
}

type Phase struct {
	ID        string   `json:"id" bson:"_id"`
	Name      string   `json:"name"`
	ProjectID string   `json:"projectID"`
	Progress  int      `json:"progress"`
	Weight    int      `json:"weight"`
	StartDate string   `json:"startDate"`
	EndDate   string   `json:"endDate"`
	States    []string `json:"states"`
	NextPhase *string  `json:"nextPhase"`
	Archived  *bool    `json:"archived"`
}

type Project struct {
	ID               string   `json:"id" bson:"_id"`
	Name             string   `json:"name"`
	Description      *string  `json:"description"`
	Progress         int      `json:"progress"`
	Weight           int      `json:"weight"`
	StartDate        string   `json:"startDate"`
	EndDate          string   `json:"endDate"`
	Archived         bool     `json:"archived"`
	CurrentPhase     *string  `json:"currentPhase"`
	OrganizationID   string   `json:"organizationID"`
	CreatedByID      string   `json:"createdByID"`
	MembersID        []string `json:"membersID"`
	ProjectLeadID    string   `json:"projectLeadID"`
	ProjectMonitorID *string  `json:"projectMonitorID"`
}

type Subtask struct {
	ID           string  `json:"id" bson:"_id"`
	Name         string  `json:"name"`
	Description  *string `json:"description"`
	Progress     *int    `json:"progress"`
	Weight       *int    `json:"weight"`
	ParentID     string  `json:"parentID"`
	PhaseID      *string `json:"phaseID"`
	OrgID        *string `json:"orgID"`
	AuthorID     *string `json:"authorID"`
	AssignedID   *string `json:"assignedID"`
	State        *string `json:"state"`
	CreateDate   string  `json:"createDate"`
	CreateTime   string  `json:"createTime"`
	DeadlineDate string  `json:"deadlineDate"`
	DeadlineTime string  `json:"deadlineTime"`
	Archived     bool    `json:"archived"`
}

type Task struct {
	ID               string     `json:"id" bson:"_id"`
	Name             string     `json:"name"`
	Description      *string    `json:"description"`
	AuthorID         string     `json:"authorID"`
	OrgID            *string    `json:"orgID"`
	PhaseID          *string    `json:"phaseID"`
	AssignedID       *string    `json:"assignedID"`
	Progress         *int       `json:"progress"`
	Weight           *int       `json:"weight"`
	State            *string    `json:"state"`
	CreateDate       string     `json:"createDate"`
	CreateTime       string     `json:"createTime"`
	DeadlineDate     string     `json:"deadlineDate"`
	DeadlineTime     string     `json:"deadlineTime"`
	Archived         bool       `json:"archived"`
	NextTasks        []*string  `json:"nextTasks"`
	Subtasks         []*Subtask `json:"subtasks"`
	Ready            *bool      `json:"ready"`
	SoonReady        *bool      `json:"soonReady"`
	FirstTask        *bool      `json:"firstTask"`
	SubtaskAssignees []*string  `json:"subtaskAssignees"`
	SubtaskDeadlines []*string  `json:"subtaskDeadlines"`
}

type TokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type UpdateSubtask struct {
	Name             *string   `json:"name"`
	Description      *string   `json:"description"`
	AssignedID       *string   `json:"assignedID"`
	OrgID            *string   `json:"orgID"`
	AuthorID         *string   `json:"authorID"`
	PhaseID          *string   `json:"phaseID"`
	Progress         *int      `json:"progress"`
	Weight           *int      `json:"weight"`
	State            *string   `json:"state"`
	DeadlineDate     *string   `json:"deadlineDate"`
	DeadlineTime     *string   `json:"deadlineTime"`
	CreateDate       *string   `json:"createDate"`
	CreateTime       *string   `json:"createTime"`
	Archived         *bool     `json:"archived"`
	ParentID         *string   `json:"parentID"`
	TasksInParallell []*string `json:"tasksInParallell"`
}

type UpdateTask struct {
	Name             *string          `json:"name"`
	Description      *string          `json:"description"`
	Progress         *int             `json:"progress"`
	OrgID            *string          `json:"orgID"`
	PhaseID          *string          `json:"phaseID"`
	AssignedID       *string          `json:"assignedID"`
	Weight           *int             `json:"weight"`
	State            *string          `json:"state"`
	DeadlineDate     *string          `json:"deadlineDate"`
	DeadlineTime     *string          `json:"deadlineTime"`
	NextTasks        []*string        `json:"nextTasks"`
	Subtasks         []*UpdateSubtask `json:"subtasks"`
	FirstTask        *bool            `json:"firstTask"`
	SubtaskAssignees []*string        `json:"subtaskAssignees"`
	TasksInParallell []*string        `json:"tasksInParallell"`
}

type User struct {
	ID    string `json:"id" bson:"_id"`
	GID   string `json:"gID"`
	Fname string `json:"fname"`
	Lname string `json:"lname"`
	Email string `json:"email"`
	Image string `json:"image"`
}
